### ISSUE TITLE
Determine JAM stack event date

### ISSUE THREAD

**Issue by joj0s** [ieee-ateith-sb/managing_the_branch#31]
Suggested date: April 6-12th

**Comment by joj0s** [comment]
@dPliakos @Kalovelo thoughts?

**Comment by Kalovelo** [comment]
Sounds good :satisfied:

**Comment by dpliakos** [comment]
~Let's rename it to "Determine period" e.g. "after Easter", "a (or two) months before semester exams" etc~

i just saw the dates. That'll work for me too
