### ISSUE TITLE
Arrange the Arduino Day schedule

### ISSUE THREAD

**Issue by joj0s** [ieee-ateith-sb/managing_the_branch#37]
I have created this google doc https://docs.google.com/document/d/1oHbjKglqdklCpKn6_z-nsG9wXWFgUFbSLbu0nvthX2s/edit?usp=sharing so that we can fill in suggested talks and workshops

**Comment by joj0s** [comment]
@dpliakos Feel free to change the OpenSCN talk info

**Comment by dpliakos** [comment]
Well... covid
