### ISSUE TITLE
Create a list of communities of our university

### ISSUE THREAD

**Issue by dpliakos** [ieee-ateith-sb/managing_the_branch#40]
Currently there is no way for someone to find what are the student communities of the IHU and how to contact them. The IHU page has a list of research groups, but student communities can not be classified as research groups. Τhey are not that formal for the main page to host them and it could take ages before we see any change to that page.

I'm proposing to add the list of communities in the iee department's apps application, until we find a more public solution.

Potential implementation:

- [x] Create a github repository and save a json with the information and static content such as images
- [ ] Use [openApps](https://github.com/theokyr/OpenApps) to show that information to the end user
- [ ] Open an issue to [IEE Apps android ](https://github.com/iamraf/IEE-Apps)application to support that 
- [ ] [optional] Use [IT_api](https://github.com/apavlidi/IT_API) to publish it as it's resource 

Problems to solve:
- Who manages it  / is responsible

**Comment by dpliakos** [comment]
@iamraf please let us know if the source is available and if the repo I added is valid

**Comment by iamraf** [comment]
@dPliakos source will be available soon under the repo link you added.

**Comment by dpliakos** [comment]
Thanks a lot!

**Comment by joj0s** [comment]
The idea sounds really good. 

>  Use openApps to show that information to the end user

@dpliakos I didn't know about that until now, does it have an existing userbase?

**Comment by dpliakos** [comment]
For the record, the work that was submitted is at https://github.com/ieee-ihuthess/ihuthess-communities
